// <auto-generated />
using EFDomainData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDomainData.Migrations
{
    [DbContext(typeof(MySampleDatabaseContext))]
    partial class MySampleDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFDomainData.Models.SampleTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SampleTable");
                });

            modelBuilder.Entity("EFDomainData.Models.SampleTableDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("SampleTableId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SampleTableId");

                    b.ToTable("SampleTableDetails");
                });

            modelBuilder.Entity("EFDomainData.Models.SampleTableDetail", b =>
                {
                    b.HasOne("EFDomainData.Models.SampleTable", "SampleTable")
                        .WithMany("SampleTableDetails")
                        .HasForeignKey("SampleTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleTable");
                });

            modelBuilder.Entity("EFDomainData.Models.SampleTable", b =>
                {
                    b.Navigation("SampleTableDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
